// Generated by `wit-bindgen` 0.50.0. DO NOT EDIT!

// Ensure that the *_component_type.o object is linked in
#ifdef __wasm32__
extern "C" void __component_type_object_force_link_strategy_grid_pricer(void);
__attribute__((used))
void __component_type_object_force_link_strategy_grid_pricer_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_strategy_grid_pricer();
}
#endif
#include "strategy_grid_pricer_cpp.h"
#include <cstdlib> // realloc

extern "C" void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size);

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}


extern "C" __attribute__((__export_name__("wasmstreet:pricing/strategy@0.1.0#compute-pnl")))
uint8_t * __wasm_export_wasmstreetX3ApricingX2FstrategyX400X2E1X2E0X23compute_pnl(uint8_t * arg0, size_t arg1, double arg2, double arg3, double arg4, double arg5, double arg6, int32_t arg7, double arg8, double arg9, int32_t arg10)
{
  static uint64_t ret_area[((88+8*sizeof(void*))+sizeof(uint64_t)-1)/sizeof(uint64_t)];
  auto base1 = arg0;
  auto len1 = arg1;
  auto result1 = wit::vector<exports::wasmstreet::pricing::strategy::Leg>::allocate(len1);
  for (unsigned i=0; i<len1; ++i) {
    auto base = base1 + i * 48;
    int32_t l0 = *((int32_t const*)(base + 32));
    auto e1 = exports::wasmstreet::pricing::strategy::Leg{(exports::wasmstreet::pricing::strategy::OptionSide)(int32_t) (*((uint8_t*) (base + 0))), (exports::wasmstreet::pricing::strategy::OptionKind)(int32_t) (*((uint8_t*) (base + 1))), (double(*((double*) (base + 8)))), (double(*((double*) (base + 16)))), (double(*((double*) (base + 24)))), (uint32_t(l0)), (double(*((double*) (base + 40)))), };
    result1.initialize(i, std::move(e1));
  }
  auto result2 = exports::wasmstreet::pricing::strategy::ComputePnl(std::move(result1), exports::wasmstreet::pricing::strategy::Scenario{(double(arg2)), (double(arg3)), (double(arg4)), (double(arg5)), (double(arg6)), (uint32_t(arg7)), (double(arg8)), (double(arg9)), (uint32_t(arg10)), });
  uint8_t* ptr3 = (uint8_t*)(&ret_area);
  if ((result2).has_value()) {
    exports::wasmstreet::pricing::strategy::GridResult payload4 = std::move(result2).value();
    *((int8_t*)(ptr3 + 0)) = (int32_t(0));
    auto&& vec5 = (payload4).pnl;
    auto ptr5 = (uint8_t*)(vec5.data());
    auto len5 = (size_t)(vec5.size());
    (payload4).pnl.leak();

    *((size_t*)(ptr3 + (8+1*sizeof(void*)))) = len5;
    *((uint8_t**)(ptr3 + 8)) = ptr5;
    *((int32_t*)(ptr3 + (8+2*sizeof(void*)))) = (int32_t((payload4).rows));
    *((int32_t*)(ptr3 + (12+2*sizeof(void*)))) = (int32_t((payload4).cols));
    auto&& vec6 = (payload4).price_axis;
    auto ptr6 = (uint8_t*)(vec6.data());
    auto len6 = (size_t)(vec6.size());
    (payload4).price_axis.leak();

    *((size_t*)(ptr3 + (16+3*sizeof(void*)))) = len6;
    *((uint8_t**)(ptr3 + (16+2*sizeof(void*)))) = ptr6;
    auto&& vec7 = (payload4).day_axis;
    auto ptr7 = (uint8_t*)(vec7.data());
    auto len7 = (size_t)(vec7.size());
    (payload4).day_axis.leak();

    *((size_t*)(ptr3 + (16+5*sizeof(void*)))) = len7;
    *((uint8_t**)(ptr3 + (16+4*sizeof(void*)))) = ptr7;
    *((double*)(ptr3 + (16+6*sizeof(void*)))) = (double((payload4).max_profit));
    *((double*)(ptr3 + (24+6*sizeof(void*)))) = (double((payload4).max_loss));
    *((double*)(ptr3 + (32+6*sizeof(void*)))) = (double((payload4).profit_pct));
    *((double*)(ptr3 + (40+6*sizeof(void*)))) = (double((payload4).pop_at_horizon));
    auto&& vec8 = (payload4).breakeven_prices;
    auto ptr8 = (uint8_t*)(vec8.data());
    auto len8 = (size_t)(vec8.size());
    (payload4).breakeven_prices.leak();

    *((size_t*)(ptr3 + (48+7*sizeof(void*)))) = len8;
    *((uint8_t**)(ptr3 + (48+6*sizeof(void*)))) = ptr8;
    *((double*)(ptr3 + (48+8*sizeof(void*)))) = (double((payload4).net_premium));
    *((double*)(ptr3 + (56+8*sizeof(void*)))) = (double((payload4).net_delta));
    *((double*)(ptr3 + (64+8*sizeof(void*)))) = (double((payload4).net_gamma));
    *((double*)(ptr3 + (72+8*sizeof(void*)))) = (double((payload4).net_vega));
    *((double*)(ptr3 + (80+8*sizeof(void*)))) = (double((payload4).net_theta));
  } else {
    wit::string payload9 = std::move(result2).error();
    *((int8_t*)(ptr3 + 0)) = (int32_t(1));
    auto&& vec10 = payload9;
    auto ptr10 = (uint8_t*)(vec10.data());
    auto len10 = (size_t)(vec10.size());
    payload9.leak();

    *((size_t*)(ptr3 + (8+1*sizeof(void*)))) = len10;
    *((uint8_t**)(ptr3 + 8)) = ptr10;
  }
  return ptr3;
}
extern "C" __attribute__((__weak__, __export_name__("cabi_post_wasmstreet:pricing/strategy@0.1.0#compute-pnl")))
void cabi_post_wasmstreetX3ApricingX2FstrategyX400X2E1X2E0X23compute_pnl(uint8_t * arg0) {
  switch ((int32_t) (int32_t) (*((uint8_t*) (arg0 + 0)))) {
    case 0: {
      uint8_t* ptr0 = *((uint8_t**) (arg0 + 8));
      size_t len0 = *((size_t*) (arg0 + (8+1*sizeof(void*))));
      for (size_t i0 = 0; i0 < len0; i0++) {
        uint8_t* base = ptr0 + i0 * 8;
        (void) base;
      }
      if (len0 > 0) {
        free((void*) (ptr0));
      }
      uint8_t* ptr1 = *((uint8_t**) (arg0 + (16+2*sizeof(void*))));
      size_t len1 = *((size_t*) (arg0 + (16+3*sizeof(void*))));
      for (size_t i1 = 0; i1 < len1; i1++) {
        uint8_t* base = ptr1 + i1 * 8;
        (void) base;
      }
      if (len1 > 0) {
        free((void*) (ptr1));
      }
      uint8_t* ptr2 = *((uint8_t**) (arg0 + (16+4*sizeof(void*))));
      size_t len2 = *((size_t*) (arg0 + (16+5*sizeof(void*))));
      for (size_t i2 = 0; i2 < len2; i2++) {
        uint8_t* base = ptr2 + i2 * 8;
        (void) base;
      }
      if (len2 > 0) {
        free((void*) (ptr2));
      }
      uint8_t* ptr3 = *((uint8_t**) (arg0 + (48+6*sizeof(void*))));
      size_t len3 = *((size_t*) (arg0 + (48+7*sizeof(void*))));
      for (size_t i3 = 0; i3 < len3; i3++) {
        uint8_t* base = ptr3 + i3 * 8;
        (void) base;
      }
      if (len3 > 0) {
        free((void*) (ptr3));
      }
      break;
    }
    case 1: {
      if ((*((size_t*) (arg0 + (8+1*sizeof(void*))))) > 0) {
        wit::string::drop_raw((void*) (*((uint8_t**) (arg0 + 8))));
      }
      break;
    }
  }
}

// Component Adapters
