// Generated by `wit-bindgen` 0.50.0. DO NOT EDIT!
#ifndef __CPP_GUEST_BINDINGS_STRATEGY_GRID_PRICER_H
#define __CPP_GUEST_BINDINGS_STRATEGY_GRID_PRICER_H
#include <cstdint>
#include <utility>
#include <expected>
#include "wit.h"
namespace wasmstreet {
  namespace pricing {
    namespace types {
      struct OptionSpec {
        double spot;
        double strike;
        double vol;
        double rate;
        double time;
      };
      struct Greeks {
        double delta;
        double gamma;
        double vega;
        double theta;
        double rho;
      };
      struct BsResult {
        double call_price;
        double put_price;
        Greeks greeks;
      };
      struct McResult {
        double price;
        double std_error;
        /// Flat row-major matrix of size (viz-paths * viz-steps).
        /// sample-paths[p * viz-steps + k] is path p at sampled step k.
        wit::vector<double> sample_paths;
        uint32_t viz_paths;
        uint32_t viz_steps;
        uint32_t num_paths;
        uint32_t num_steps;
      };
      // export_interface Interface(Id { idx: 17 })
    }
  }
}
namespace exports {
  namespace wasmstreet {
    namespace pricing {
      namespace strategy {
        using OptionSpec = ::wasmstreet::pricing::types::OptionSpec;
        enum class OptionSide : uint8_t {
          kBuy = 0,
          kSell = 1,
        };

        enum class OptionKind : uint8_t {
          kCall = 0,
          kPut = 1,
        };

        struct Leg {
          OptionSide side;
          OptionKind kind;
          double strike;
          double expiration_days;
          double iv;
          uint32_t units;
          double entry_premium;
        };
        struct Scenario {
          double spot;
          double rate;
          double vol;
          double price_min;
          double price_max;
          uint32_t price_steps;
          double days_min;
          double days_max;
          uint32_t day_steps;
        };
        struct GridResult {
          /// Flat row-major matrix, length = price-steps * day-steps.
          /// pnl[i * day-steps + j] is the dollar P&L at price-axis[i] and day-axis[j].
          wit::vector<double> pnl;
          uint32_t rows;
          uint32_t cols;
          wit::vector<double> price_axis;
          wit::vector<double> day_axis;
          double max_profit;
          double max_loss;
          /// Fraction of grid cells where the strategy is profitable (0–100).
          /// This is the geometric/grid-coverage measure — does NOT correspond
          /// to a probability of profit because the grid is uniformly sampled
          /// over the user-chosen price range.
          double profit_pct;
          /// Lognormal-weighted probability that the underlying lands in the
          /// profitable price region at the horizon, given scenario vol + rate.
          /// Interpreted as a true PoP under risk-neutral lognormal dynamics.
          double pop_at_horizon;
          wit::vector<double> breakeven_prices;
          double net_premium;
          double net_delta;
          double net_gamma;
          double net_vega;
          double net_theta;
        };
        std::expected<GridResult, wit::string> ComputePnl(wit::vector<Leg> legs, Scenario scen);
      }
    }
  }
}

#endif
