// Generated by `wit-bindgen` 0.50.0. DO NOT EDIT!

// Ensure that the *_component_type.o object is linked in
#ifdef __wasm32__
extern "C" void __component_type_object_force_link_strategy_search_pricer(void);
__attribute__((used))
void __component_type_object_force_link_strategy_search_pricer_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_strategy_search_pricer();
}
#endif
#include "strategy_search_pricer_cpp.h"
#include <cstdlib> // realloc

extern "C" void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size);

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}


extern "C" __attribute__((import_module("wasmstreet:pricing/strategy@0.1.0")))
__attribute__((import_name("compute-pnl")))
void __wasm_import_wasmstreetX3ApricingX2FstrategyX400X2E1X2E0X00compute_pnl(uint8_t *, size_t, double, double, double, double, double, int32_t, double, double, int32_t, uint8_t *);
std::expected<wasmstreet::pricing::strategy::GridResult, wit::string> wasmstreet::pricing::strategy::ComputePnl(std::span<Leg const> legs, Scenario scen)
{
  uint64_t ret_area[((88+8*sizeof(void*))+sizeof(uint64_t)-1)/sizeof(uint64_t)];
  auto&& vec0 = legs;
  auto ptr0 = (uint8_t*)(vec0.data());
  auto len0 = (size_t)(vec0.size());
  for (size_t i = 0; i < len0; ++i) {
    auto base = ptr0 + i * 48;
    auto&& IterElem = vec0[i];
    *((int8_t*)(base + 0)) = int32_t((IterElem).side);
    *((int8_t*)(base + 1)) = int32_t((IterElem).kind);
    *((double*)(base + 8)) = (double((IterElem).strike));
    *((double*)(base + 16)) = (double((IterElem).expiration_days));
    *((double*)(base + 24)) = (double((IterElem).iv));
    *((int32_t*)(base + 32)) = (int32_t((IterElem).units));
    *((double*)(base + 40)) = (double((IterElem).entry_premium));

  }
  uint8_t* ptr1 = (uint8_t*)(&ret_area);
  __wasm_import_wasmstreetX3ApricingX2FstrategyX400X2E1X2E0X00compute_pnl(std::move(ptr0), std::move(len0), (double((scen).spot)), (double((scen).rate)), (double((scen).vol)), (double((scen).price_min)), (double((scen).price_max)), (int32_t((scen).price_steps)), (double((scen).days_min)), (double((scen).days_max)), (int32_t((scen).day_steps)), std::move(ptr1));
  std::optional<std::expected<GridResult, wit::string>> result9_opt;
  if ((int32_t) (*((uint8_t*) (ptr1 + 0)))==0) {
    auto len2 = *((size_t*) (ptr1 + (8+1*sizeof(void*))));
    int32_t l3 = *((int32_t const*)(ptr1 + (8+2*sizeof(void*))));
    int32_t l4 = *((int32_t const*)(ptr1 + (12+2*sizeof(void*))));
    auto len5 = *((size_t*) (ptr1 + (16+3*sizeof(void*))));
    auto len6 = *((size_t*) (ptr1 + (16+5*sizeof(void*))));
    auto len7 = *((size_t*) (ptr1 + (48+7*sizeof(void*))));

    result9_opt.emplace(std::expected<GridResult, wit::string>(GridResult{wit::vector<double>((double*)(*((uint8_t**) (ptr1 + 8))), len2), (uint32_t(l3)), (uint32_t(l4)), wit::vector<double>((double*)(*((uint8_t**) (ptr1 + (16+2*sizeof(void*))))), len5), wit::vector<double>((double*)(*((uint8_t**) (ptr1 + (16+4*sizeof(void*))))), len6), (double(*((double*) (ptr1 + (16+6*sizeof(void*)))))), (double(*((double*) (ptr1 + (24+6*sizeof(void*)))))), (double(*((double*) (ptr1 + (32+6*sizeof(void*)))))), (double(*((double*) (ptr1 + (40+6*sizeof(void*)))))), wit::vector<double>((double*)(*((uint8_t**) (ptr1 + (48+6*sizeof(void*))))), len7), (double(*((double*) (ptr1 + (48+8*sizeof(void*)))))), (double(*((double*) (ptr1 + (56+8*sizeof(void*)))))), (double(*((double*) (ptr1 + (64+8*sizeof(void*)))))), (double(*((double*) (ptr1 + (72+8*sizeof(void*)))))), (double(*((double*) (ptr1 + (80+8*sizeof(void*)))))), }));
  } else {
    auto len8 = *((size_t*) (ptr1 + (8+1*sizeof(void*))));


    result9_opt.emplace(std::unexpected{wit::string((char const*)(*((uint8_t**) (ptr1 + 8))), len8)});
  }
  std::expected<GridResult, wit::string> result9 = std::move(*result9_opt);
  auto result10 = std::move(result9);
  return result10;
}
extern "C" __attribute__((__export_name__("wasmstreet:pricing/search@0.1.0#search")))
uint8_t * __wasm_export_wasmstreetX3ApricingX2FsearchX400X2E1X2E0X23search(uint8_t * arg0, size_t arg1, double arg2, double arg3, double arg4, double arg5, double arg6, int32_t arg7, double arg8, double arg9, int32_t arg10, int32_t arg11, uint8_t * arg12, size_t arg13)
{
  static uintptr_t ret_area[((8+3*sizeof(void*))+sizeof(uintptr_t)-1)/sizeof(uintptr_t)];
  auto base0 = arg0;
  auto len0 = arg1;
  auto result0 = wit::vector<exports::wasmstreet::pricing::search::SearchContract>::allocate(len0);
  for (unsigned i=0; i<len0; ++i) {
    auto base = base0 + i * 40;
    auto e0 = exports::wasmstreet::pricing::search::SearchContract{(wasmstreet::pricing::strategy::OptionKind)(int32_t) (*((uint8_t*) (base + 0))), (double(*((double*) (base + 8)))), (double(*((double*) (base + 16)))), (double(*((double*) (base + 24)))), (double(*((double*) (base + 32)))), };
    result0.initialize(i, std::move(e0));
  }
  auto len1 = arg13;

  auto result2 = exports::wasmstreet::pricing::search::Search(std::move(result0), exports::wasmstreet::pricing::search::SearchConfig{(double(arg2)), (double(arg3)), (double(arg4)), (double(arg5)), (double(arg6)), (uint32_t(arg7)), (double(arg8)), (double(arg9)), (uint32_t(arg10)), (uint32_t(arg11)), wit::string((char const*)(arg12), len1), });
  uint8_t* ptr3 = (uint8_t*)(&ret_area);
  if ((result2).has_value()) {
    exports::wasmstreet::pricing::search::SearchResult payload4 = std::move(result2).value();
    *((int8_t*)(ptr3 + 0)) = (int32_t(0));
    *((int32_t*)(ptr3 + sizeof(void*))) = (int32_t((payload4).evaluated));
    *((int32_t*)(ptr3 + (4+1*sizeof(void*)))) = (int32_t((payload4).elapsed_ms));
    auto&& vec8 = (payload4).ranked;
    auto ptr8 = (uint8_t*)(vec8.data());
    auto len8 = (size_t)(vec8.size());
    for (size_t i = 0; i < len8; ++i) {
      auto base = ptr8 + i * (48+6*sizeof(void*));
      auto&& IterElem = vec8[i];
      auto&& vec5 = (IterElem).name;
      auto ptr5 = (uint8_t*)(vec5.data());
      auto len5 = (size_t)(vec5.size());
      (IterElem).name.leak();

      *((size_t*)(base + sizeof(void*))) = len5;
      *((uint8_t**)(base + 0)) = ptr5;
      auto&& vec6 = (IterElem).kind_key;
      auto ptr6 = (uint8_t*)(vec6.data());
      auto len6 = (size_t)(vec6.size());
      (IterElem).kind_key.leak();

      *((size_t*)(base + (3*sizeof(void*)))) = len6;
      *((uint8_t**)(base + (2*sizeof(void*)))) = ptr6;
      auto&& vec7 = (IterElem).legs;
      auto ptr7 = (uint8_t*)(vec7.data());
      auto len7 = (size_t)(vec7.size());
      for (size_t i = 0; i < len7; ++i) {
        auto base = ptr7 + i * 48;
        auto&& IterElem = vec7[i];
        *((int8_t*)(base + 0)) = int32_t((IterElem).side);
        *((int8_t*)(base + 1)) = int32_t((IterElem).kind);
        *((double*)(base + 8)) = (double((IterElem).strike));
        *((double*)(base + 16)) = (double((IterElem).expiration_days));
        *((double*)(base + 24)) = (double((IterElem).iv));
        *((int32_t*)(base + 32)) = (int32_t((IterElem).units));
        *((double*)(base + 40)) = (double((IterElem).entry_premium));

      }
      (IterElem).legs.leak();

      *((size_t*)(base + (5*sizeof(void*)))) = len7;
      *((uint8_t**)(base + (4*sizeof(void*)))) = ptr7;
      *((double*)(base + (6*sizeof(void*)))) = (double((IterElem).max_profit));
      *((double*)(base + (8+6*sizeof(void*)))) = (double((IterElem).max_loss));
      *((double*)(base + (16+6*sizeof(void*)))) = (double((IterElem).profit_pct));
      *((double*)(base + (24+6*sizeof(void*)))) = (double((IterElem).pop_at_horizon));
      *((double*)(base + (32+6*sizeof(void*)))) = (double((IterElem).net_premium));
      *((double*)(base + (40+6*sizeof(void*)))) = (double((IterElem).score));

    }
    (payload4).ranked.leak();

    *((size_t*)(ptr3 + (8+2*sizeof(void*)))) = len8;
    *((uint8_t**)(ptr3 + (8+1*sizeof(void*)))) = ptr8;
  } else {
    wit::string payload9 = std::move(result2).error();
    *((int8_t*)(ptr3 + 0)) = (int32_t(1));
    auto&& vec10 = payload9;
    auto ptr10 = (uint8_t*)(vec10.data());
    auto len10 = (size_t)(vec10.size());
    payload9.leak();

    *((size_t*)(ptr3 + (2*sizeof(void*)))) = len10;
    *((uint8_t**)(ptr3 + sizeof(void*))) = ptr10;
  }
  return ptr3;
}
extern "C" __attribute__((__weak__, __export_name__("cabi_post_wasmstreet:pricing/search@0.1.0#search")))
void cabi_post_wasmstreetX3ApricingX2FsearchX400X2E1X2E0X23search(uint8_t * arg0) {
  switch ((int32_t) (int32_t) (*((uint8_t*) (arg0 + 0)))) {
    case 0: {
      uint8_t* ptr1 = *((uint8_t**) (arg0 + (8+1*sizeof(void*))));
      size_t len1 = *((size_t*) (arg0 + (8+2*sizeof(void*))));
      for (size_t i1 = 0; i1 < len1; i1++) {
        uint8_t* base = ptr1 + i1 * (48+6*sizeof(void*));
        (void) base;
        if ((*((size_t*) (base + sizeof(void*)))) > 0) {
          wit::string::drop_raw((void*) (*((uint8_t**) (base + 0))));
        }
        if ((*((size_t*) (base + (3*sizeof(void*))))) > 0) {
          wit::string::drop_raw((void*) (*((uint8_t**) (base + (2*sizeof(void*))))));
        }
        uint8_t* ptr0 = *((uint8_t**) (base + (4*sizeof(void*))));
        size_t len0 = *((size_t*) (base + (5*sizeof(void*))));
        for (size_t i0 = 0; i0 < len0; i0++) {
          uint8_t* base = ptr0 + i0 * 48;
          (void) base;
        }
        if (len0 > 0) {
          free((void*) (ptr0));
        }
      }
      if (len1 > 0) {
        free((void*) (ptr1));
      }
      break;
    }
    case 1: {
      if ((*((size_t*) (arg0 + (2*sizeof(void*))))) > 0) {
        wit::string::drop_raw((void*) (*((uint8_t**) (arg0 + sizeof(void*)))));
      }
      break;
    }
  }
}

// Component Adapters
