// Generated by `wit-bindgen` 0.50.0. DO NOT EDIT!
#ifndef __CPP_GUEST_BINDINGS_BT_PRICER_H
#define __CPP_GUEST_BINDINGS_BT_PRICER_H
#include <cstdint>
#include <utility>
#include <expected>
#include "wit.h"
namespace wasmstreet {
  namespace pricing {
    namespace types {
      struct OptionSpec {
        double spot;
        double strike;
        double vol;
        double rate;
        double time;
      };
      struct Greeks {
        double delta;
        double gamma;
        double vega;
        double theta;
        double rho;
      };
      struct BsResult {
        double call_price;
        double put_price;
        Greeks greeks;
      };
      struct McResult {
        double price;
        double std_error;
        /// Flat row-major matrix of size (viz-paths * viz-steps).
        /// sample-paths[p * viz-steps + k] is path p at sampled step k.
        wit::vector<double> sample_paths;
        uint32_t viz_paths;
        uint32_t viz_steps;
        uint32_t num_paths;
        uint32_t num_steps;
      };
      // export_interface Interface(Id { idx: 15 })
    }
  }
}
namespace exports {
  namespace wasmstreet {
    namespace pricing {
      namespace binomial_tree {
        using OptionSpec = ::wasmstreet::pricing::types::OptionSpec;
        enum class OptionType : uint8_t {
          kCall = 0,
          kPut = 1,
        };

        struct BtSpec {
          ::wasmstreet::pricing::types::OptionSpec underlying;
          uint32_t steps;
          bool american;
          OptionType kind;
        };
        struct BtResult {
          double price;
          uint32_t steps;
          /// Flat triangular array of node values, size (steps+1)*(steps+2)/2.
          /// Node at level n, position i (0 <= i <= n) is at index n*(n+1)/2 + i.
          /// Stores the option value at that node from the backward induction.
          wit::vector<double> node_values;
          /// Spot prices at each node, same indexing as node-values.
          wit::vector<double> node_spots;
        };
        std::expected<BtResult, wit::string> Price(BtSpec spec);
      }
    }
  }
}

#endif
