// Generated by `wit-bindgen` 0.50.0. DO NOT EDIT!

// Ensure that the *_component_type.o object is linked in
#ifdef __wasm32__
extern "C" void __component_type_object_force_link_bt_pricer(void);
__attribute__((used))
void __component_type_object_force_link_bt_pricer_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_bt_pricer();
}
#endif
#include "bt_pricer_cpp.h"
#include <cstdlib> // realloc

extern "C" void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size);

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}


extern "C" __attribute__((__export_name__("wasmstreet:pricing/binomial-tree@0.1.0#price")))
uint8_t * __wasm_export_wasmstreetX3ApricingX2Fbinomial_treeX400X2E1X2E0X23price(double arg0, double arg1, double arg2, double arg3, double arg4, int32_t arg5, int32_t arg6, int32_t arg7)
{
  static uint64_t ret_area[((24+4*sizeof(void*))+sizeof(uint64_t)-1)/sizeof(uint64_t)];
  auto result0 = exports::wasmstreet::pricing::binomial_tree::Price(exports::wasmstreet::pricing::binomial_tree::BtSpec{wasmstreet::pricing::types::OptionSpec{(double(arg0)), (double(arg1)), (double(arg2)), (double(arg3)), (double(arg4)), }, (uint32_t(arg5)), (bool(arg6)), (exports::wasmstreet::pricing::binomial_tree::OptionType)arg7, });
  uint8_t* ptr1 = (uint8_t*)(&ret_area);
  if ((result0).has_value()) {
    exports::wasmstreet::pricing::binomial_tree::BtResult payload2 = std::move(result0).value();
    *((int8_t*)(ptr1 + 0)) = (int32_t(0));
    *((double*)(ptr1 + 8)) = (double((payload2).price));
    *((int32_t*)(ptr1 + 16)) = (int32_t((payload2).steps));
    auto&& vec3 = (payload2).node_values;
    auto ptr3 = (uint8_t*)(vec3.data());
    auto len3 = (size_t)(vec3.size());
    (payload2).node_values.leak();

    *((size_t*)(ptr1 + (16+2*sizeof(void*)))) = len3;
    *((uint8_t**)(ptr1 + (16+1*sizeof(void*)))) = ptr3;
    auto&& vec4 = (payload2).node_spots;
    auto ptr4 = (uint8_t*)(vec4.data());
    auto len4 = (size_t)(vec4.size());
    (payload2).node_spots.leak();

    *((size_t*)(ptr1 + (16+4*sizeof(void*)))) = len4;
    *((uint8_t**)(ptr1 + (16+3*sizeof(void*)))) = ptr4;
  } else {
    wit::string payload5 = std::move(result0).error();
    *((int8_t*)(ptr1 + 0)) = (int32_t(1));
    auto&& vec6 = payload5;
    auto ptr6 = (uint8_t*)(vec6.data());
    auto len6 = (size_t)(vec6.size());
    payload5.leak();

    *((size_t*)(ptr1 + (8+1*sizeof(void*)))) = len6;
    *((uint8_t**)(ptr1 + 8)) = ptr6;
  }
  return ptr1;
}
extern "C" __attribute__((__weak__, __export_name__("cabi_post_wasmstreet:pricing/binomial-tree@0.1.0#price")))
void cabi_post_wasmstreetX3ApricingX2Fbinomial_treeX400X2E1X2E0X23price(uint8_t * arg0) {
  switch ((int32_t) (int32_t) (*((uint8_t*) (arg0 + 0)))) {
    case 0: {
      uint8_t* ptr0 = *((uint8_t**) (arg0 + (16+1*sizeof(void*))));
      size_t len0 = *((size_t*) (arg0 + (16+2*sizeof(void*))));
      for (size_t i0 = 0; i0 < len0; i0++) {
        uint8_t* base = ptr0 + i0 * 8;
        (void) base;
      }
      if (len0 > 0) {
        free((void*) (ptr0));
      }
      uint8_t* ptr1 = *((uint8_t**) (arg0 + (16+3*sizeof(void*))));
      size_t len1 = *((size_t*) (arg0 + (16+4*sizeof(void*))));
      for (size_t i1 = 0; i1 < len1; i1++) {
        uint8_t* base = ptr1 + i1 * 8;
        (void) base;
      }
      if (len1 > 0) {
        free((void*) (ptr1));
      }
      break;
    }
    case 1: {
      if ((*((size_t*) (arg0 + (8+1*sizeof(void*))))) > 0) {
        wit::string::drop_raw((void*) (*((uint8_t**) (arg0 + 8))));
      }
      break;
    }
  }
}

// Component Adapters
