// Generated by `wit-bindgen` 0.50.0. DO NOT EDIT!
#ifndef __CPP_GUEST_BINDINGS_MC_PRICER_H
#define __CPP_GUEST_BINDINGS_MC_PRICER_H
#include <cstdint>
#include <utility>
#include <expected>
#include "wit.h"
namespace wasmstreet {
  namespace pricing {
    namespace types {
      struct OptionSpec {
        double spot;
        double strike;
        double vol;
        double rate;
        double time;
      };
      struct Greeks {
        double delta;
        double gamma;
        double vega;
        double theta;
        double rho;
      };
      struct BsResult {
        double call_price;
        double put_price;
        Greeks greeks;
      };
      struct McResult {
        double price;
        double std_error;
        /// Flat row-major matrix of size (viz-paths * viz-steps).
        /// sample-paths[p * viz-steps + k] is path p at sampled step k.
        wit::vector<double> sample_paths;
        uint32_t viz_paths;
        uint32_t viz_steps;
        uint32_t num_paths;
        uint32_t num_steps;
      };
      // export_interface Interface(Id { idx: 14 })
    }
  }
}
namespace exports {
  namespace wasmstreet {
    namespace pricing {
      namespace monte_carlo {
        using OptionSpec = ::wasmstreet::pricing::types::OptionSpec;
        using McResult = ::wasmstreet::pricing::types::McResult;
        struct McSpec {
          ::wasmstreet::pricing::types::OptionSpec underlying;
          uint32_t num_paths;
          uint32_t num_steps;
          uint64_t seed;
        };
        std::expected<::wasmstreet::pricing::types::McResult, wit::string> PriceAsianCall(McSpec spec);
      }
    }
  }
}

#endif
