// Generated by `wit-bindgen` 0.50.0. DO NOT EDIT!

// Ensure that the *_component_type.o object is linked in
#ifdef __wasm32__
extern "C" void __component_type_object_force_link_mc_pricer(void);
__attribute__((used))
void __component_type_object_force_link_mc_pricer_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_mc_pricer();
}
#endif
#include "mc_pricer_cpp.h"
#include <cstdlib> // realloc

extern "C" void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size);

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}


extern "C" __attribute__((__export_name__("wasmstreet:pricing/monte-carlo@0.1.0#price-asian-call")))
uint8_t * __wasm_export_wasmstreetX3ApricingX2Fmonte_carloX400X2E1X2E0X23price_asian_call(double arg0, double arg1, double arg2, double arg3, double arg4, int32_t arg5, int32_t arg6, int64_t arg7)
{
  static uint64_t ret_area[((40+2*sizeof(void*))+sizeof(uint64_t)-1)/sizeof(uint64_t)];
  auto result0 = exports::wasmstreet::pricing::monte_carlo::PriceAsianCall(exports::wasmstreet::pricing::monte_carlo::McSpec{wasmstreet::pricing::types::OptionSpec{(double(arg0)), (double(arg1)), (double(arg2)), (double(arg3)), (double(arg4)), }, (uint32_t(arg5)), (uint32_t(arg6)), (uint64_t(arg7)), });
  uint8_t* ptr1 = (uint8_t*)(&ret_area);
  if ((result0).has_value()) {
    wasmstreet::pricing::types::McResult payload2 = std::move(result0).value();
    *((int8_t*)(ptr1 + 0)) = (int32_t(0));
    *((double*)(ptr1 + 8)) = (double((payload2).price));
    *((double*)(ptr1 + 16)) = (double((payload2).std_error));
    auto&& vec3 = (payload2).sample_paths;
    auto ptr3 = (uint8_t*)(vec3.data());
    auto len3 = (size_t)(vec3.size());
    (payload2).sample_paths.leak();

    *((size_t*)(ptr1 + (24+1*sizeof(void*)))) = len3;
    *((uint8_t**)(ptr1 + 24)) = ptr3;
    *((int32_t*)(ptr1 + (24+2*sizeof(void*)))) = (int32_t((payload2).viz_paths));
    *((int32_t*)(ptr1 + (28+2*sizeof(void*)))) = (int32_t((payload2).viz_steps));
    *((int32_t*)(ptr1 + (32+2*sizeof(void*)))) = (int32_t((payload2).num_paths));
    *((int32_t*)(ptr1 + (36+2*sizeof(void*)))) = (int32_t((payload2).num_steps));
  } else {
    wit::string payload4 = std::move(result0).error();
    *((int8_t*)(ptr1 + 0)) = (int32_t(1));
    auto&& vec5 = payload4;
    auto ptr5 = (uint8_t*)(vec5.data());
    auto len5 = (size_t)(vec5.size());
    payload4.leak();

    *((size_t*)(ptr1 + (8+1*sizeof(void*)))) = len5;
    *((uint8_t**)(ptr1 + 8)) = ptr5;
  }
  return ptr1;
}
extern "C" __attribute__((__weak__, __export_name__("cabi_post_wasmstreet:pricing/monte-carlo@0.1.0#price-asian-call")))
void cabi_post_wasmstreetX3ApricingX2Fmonte_carloX400X2E1X2E0X23price_asian_call(uint8_t * arg0) {
  switch ((int32_t) (int32_t) (*((uint8_t*) (arg0 + 0)))) {
    case 0: {
      uint8_t* ptr0 = *((uint8_t**) (arg0 + 24));
      size_t len0 = *((size_t*) (arg0 + (24+1*sizeof(void*))));
      for (size_t i0 = 0; i0 < len0; i0++) {
        uint8_t* base = ptr0 + i0 * 8;
        (void) base;
      }
      if (len0 > 0) {
        free((void*) (ptr0));
      }
      break;
    }
    case 1: {
      if ((*((size_t*) (arg0 + (8+1*sizeof(void*))))) > 0) {
        wit::string::drop_raw((void*) (*((uint8_t**) (arg0 + 8))));
      }
      break;
    }
  }
}

// Component Adapters
