// Generated by `wit-bindgen` 0.50.0. DO NOT EDIT!
#ifndef __CPP_GUEST_BINDINGS_BS_PRICER_H
#define __CPP_GUEST_BINDINGS_BS_PRICER_H
#include <cstdint>
#include <utility>
#include <expected>
#include "wit.h"
namespace wasmstreet {
  namespace pricing {
    namespace types {
      struct OptionSpec {
        double spot;
        double strike;
        double vol;
        double rate;
        double time;
      };
      struct Greeks {
        double delta;
        double gamma;
        double vega;
        double theta;
        double rho;
      };
      struct BsResult {
        double call_price;
        double put_price;
        Greeks greeks;
      };
      struct McResult {
        double price;
        double std_error;
        /// Flat row-major matrix of size (viz-paths * viz-steps).
        /// sample-paths[p * viz-steps + k] is path p at sampled step k.
        wit::vector<double> sample_paths;
        uint32_t viz_paths;
        uint32_t viz_steps;
        uint32_t num_paths;
        uint32_t num_steps;
      };
      // export_interface Interface(Id { idx: 13 })
    }
  }
}
namespace exports {
  namespace wasmstreet {
    namespace pricing {
      namespace black_scholes {
        using OptionSpec = ::wasmstreet::pricing::types::OptionSpec;
        using BsResult = ::wasmstreet::pricing::types::BsResult;
        std::expected<::wasmstreet::pricing::types::BsResult, wit::string> PriceEuropean(::wasmstreet::pricing::types::OptionSpec spec);
      }
    }
  }
}

#endif
