// Generated by `wit-bindgen` 0.50.0. DO NOT EDIT!

// Ensure that the *_component_type.o object is linked in
#ifdef __wasm32__
extern "C" void __component_type_object_force_link_bs_pricer(void);
__attribute__((used))
void __component_type_object_force_link_bs_pricer_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_bs_pricer();
}
#endif
#include "bs_pricer_cpp.h"
#include <cstdlib> // realloc

extern "C" void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size);

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}


extern "C" __attribute__((__export_name__("wasmstreet:pricing/black-scholes@0.1.0#price-european")))
uint8_t * __wasm_export_wasmstreetX3ApricingX2Fblack_scholesX400X2E1X2E0X23price_european(double arg0, double arg1, double arg2, double arg3, double arg4)
{
  static uint64_t ret_area[(64+sizeof(uint64_t)-1)/sizeof(uint64_t)];
  auto result0 = exports::wasmstreet::pricing::black_scholes::PriceEuropean(wasmstreet::pricing::types::OptionSpec{(double(arg0)), (double(arg1)), (double(arg2)), (double(arg3)), (double(arg4)), });
  uint8_t* ptr1 = (uint8_t*)(&ret_area);
  if ((result0).has_value()) {
    wasmstreet::pricing::types::BsResult payload2 = std::move(result0).value();
    *((int8_t*)(ptr1 + 0)) = (int32_t(0));
    *((double*)(ptr1 + 8)) = (double((payload2).call_price));
    *((double*)(ptr1 + 16)) = (double((payload2).put_price));
    *((double*)(ptr1 + 24)) = (double(((payload2).greeks).delta));
    *((double*)(ptr1 + 32)) = (double(((payload2).greeks).gamma));
    *((double*)(ptr1 + 40)) = (double(((payload2).greeks).vega));
    *((double*)(ptr1 + 48)) = (double(((payload2).greeks).theta));
    *((double*)(ptr1 + 56)) = (double(((payload2).greeks).rho));
  } else {
    wit::string payload3 = std::move(result0).error();
    *((int8_t*)(ptr1 + 0)) = (int32_t(1));
    auto&& vec4 = payload3;
    auto ptr4 = (uint8_t*)(vec4.data());
    auto len4 = (size_t)(vec4.size());
    payload3.leak();

    *((size_t*)(ptr1 + (8+1*sizeof(void*)))) = len4;
    *((uint8_t**)(ptr1 + 8)) = ptr4;
  }
  return ptr1;
}
extern "C" __attribute__((__weak__, __export_name__("cabi_post_wasmstreet:pricing/black-scholes@0.1.0#price-european")))
void cabi_post_wasmstreetX3ApricingX2Fblack_scholesX400X2E1X2E0X23price_european(uint8_t * arg0) {
  switch ((int32_t) (int32_t) (*((uint8_t*) (arg0 + 0)))) {
    case 0: {
      break;
    }
    case 1: {
      if ((*((size_t*) (arg0 + (8+1*sizeof(void*))))) > 0) {
        wit::string::drop_raw((void*) (*((uint8_t**) (arg0 + 8))));
      }
      break;
    }
  }
}

// Component Adapters
